CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number VARCHAR(40) NOT NULL UNIQUE,
  customer_code VARCHAR(40) NOT NULL,
  product_code VARCHAR(40) NOT NULL,
  quantity INTEGER NOT NULL,
  unit_price DECIMAL(12,2) NOT NULL,
  status VARCHAR(20) NOT NULL,
  order_date TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_orders_customer_date ON orders(customer_code, order_date);
CREATE INDEX IF NOT EXISTS idx_orders_product_status ON orders(product_code, status);

CREATE TABLE IF NOT EXISTS shipping (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL UNIQUE,
  address_line1 VARCHAR(200) NOT NULL,
  address_line2 VARCHAR(200),
  city VARCHAR(80) NOT NULL,
  state VARCHAR(80) NOT NULL,
  postal_code VARCHAR(20) NOT NULL,
  country VARCHAR(60) NOT NULL,
  status VARCHAR(20) NOT NULL,
  shipped_date DATE,
  delivery_date DATE,
  CONSTRAINT fk_shipping_order FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE INDEX IF NOT EXISTS idx_shipping_status ON shipping(status);
CREATE INDEX IF NOT EXISTS idx_shipping_postal_code ON shipping(postal_code);

CREATE TABLE IF NOT EXISTS coupon (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coupon_code VARCHAR(40) NOT NULL UNIQUE,
  discount_percentage DECIMAL(5,2) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  valid_from DATE,
  valid_until DATE,
  description VARCHAR(200)
);

CREATE INDEX IF NOT EXISTS idx_coupon_code ON coupon(coupon_code);

CREATE TABLE IF NOT EXISTS state_tax (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  state_code VARCHAR(10) NOT NULL UNIQUE,
  state_name VARCHAR(80) NOT NULL,
  tax_percentage DECIMAL(5,2) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_state_tax_code ON state_tax(state_code);

ALTER TABLE coupon ADD COLUMN IF NOT EXISTS combinable BOOLEAN NOT NULL DEFAULT FALSE;
